name: ubuntu + KDE Plasma + Tailscale (Optimized)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup-gui-runner:
    runs-on: ubuntu-22.04
    env:
      TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
      USERNAME: runner
      PASSWORD: runner  # one password for system + KDE session
      TAILSCALE_HOSTNAME: gh-plasma-${{ github.run_id }}

    steps:
      - uses: actions/checkout@v4

      - name: Prepare user & system
        run: |
          echo ">>> Updating system and setting password..."
          echo "${USERNAME}:${PASSWORD}" | sudo chpasswd
          echo "${USERNAME} ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/${USERNAME}
          sudo apt-get update -qq
          sudo apt-get -y -qq upgrade
          # Lightweight tweaks to avoid heavy animations
          sudo apt-get install -y -qq ufw curl

      - name: Install lightweight KDE Plasma + xrdp
        run: |
          echo ">>> Installing minimal KDE Plasma..."
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
            plasma-desktop sddm xorg dbus-x11 xrdp

          # Use SDDM as display manager and set same password for login
          sudo systemctl enable sddm
          echo "startplasma-x11" | sudo tee /home/${USERNAME}/.xsession
          sudo chown ${USERNAME}:${USERNAME} /home/${USERNAME}/.xsession
          sudo systemctl enable --now xrdp
          sudo systemctl restart xrdp

      - name: Install and start Tailscale
        run: |
          echo ">>> Installing Tailscale..."
          curl -fsSL https://tailscale.com/install.sh | sudo sh
          sudo tailscale up --authkey "${TAILSCALE_AUTHKEY}" \
                            --hostname "${TAILSCALE_HOSTNAME}" \
                            --ephemeral
          sudo tailscale ip -4

      - name: Harden network
        run: |
          echo ">>> Restricting inbound access to Tailscale only..."
          sudo ufw default deny incoming
          sudo ufw default allow outgoing
          sudo ufw allow in on tailscale0
          sudo ufw enable || true

      - name: Connection + Keep Alive
        run: |
          echo "=== FINAL CONNECTION INFO ==="
          echo "USERNAME: ${USERNAME}"
          echo "PASSWORD: ${PASSWORD}"
          echo "Tailscale IPv4:"
          sudo tailscale ip -4 || true
          echo "Connect with any RDP client using the IP above."
          echo "This runner stays alive for up to 6 hours."
          while true; do sleep 600; done
